Fix SSH key permissions

diff --git a/azure-pipeline.yaml b/azure-pipeline.yaml
--- a/azure-pipeline.yaml
+++ b/azure-pipeline.yaml
@@ -29,7 +29,10 @@ stages:
               mkdir -p ~/.ssh
               cp $(download_ssh_key.secureFilePath) ~/.ssh/id_ed25519
               chmod 600 ~/.ssh/id_ed25519
-              echo "StrictHostKeyChecking no" > ~/.ssh/config
+              chmod 700 ~/.ssh
+              echo "StrictHostKeyChecking no" >> ~/.ssh/config
+              echo "IdentityFile ~/.ssh/id_ed25519" >> ~/.ssh/config
+              ssh-keygen -y -f ~/.ssh/id_ed25519 > /dev/null && echo "Key is valid" || echo "Key is invalid"
             displayName: "Setup SSH Private Key"
 
           - script: |
